trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Firstjob
    steps:
    - bash: echo Build First job
    - bash: echo $(PipilineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.BuildSourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStaging)
    - bash: java -version
    - bash: node --version    
    - bash: python --version
    - bash: mvn -version  
    - bash: ls -R $(Build.ArtifactStaging)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStaging)'
    - bash: ls -R $(Build.ArtifactStaging)

  # - job: Secondjob
  #   steps:
  #   - bash: echo Build Second job
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevdeployJob
#     steps:
#     - bash: echo $(environment)Deploy job
# - stage: QaDeploy
#   variables:
#     environment: Qa
#   dependsOn: Build
#   jobs:
#   - job: QaDeployJob
#     steps:
#     - bash: echo $(environment)Deploy job
# - stage: ProdDeploy
#   variables:
#     environment: Prod
#   dependsOn:
#   - DevDeploy
#   - QaDeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - bash: echo $(environment)Deploy job
